### ISSUE TITLE
How do I generate a lot of images?

### ISSUE THREAD

**Issue by taki0112** [minhnhat93/tf-SNDCGAN#1]
How do I generate a lot of images?

```python
python train.py
```
if max_iter = 100000, then only 64 images are generated

I want to generate a lot of features, but also a lot of images.

how ?

**Comment by minhnhat93** [comment]
To generate a lot of images you just need to load the model, generate images from random noise and save it back using the save_images function but with bigger sample_images array (see line 91, 92 https://github.com/minhnhat93/tf-SNDCGAN/blob/master/train.py#L91). The train.py file has all the above functionalities. You can modify the train.py file, remove all the extra training or just go into debug mode, break at line 91 and change sample_noise to some bigger array like np.random.random((1000, 128)). Note that there may not be enough memory available on GPU to generate all your images at once though so you may need to generate multiple times.

**Comment by taki0112** [comment]
thank you
